---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-gke-nightly-cluster-ubuntu-latest-wego-wego-test-app-72khhde7
  namespace: wego-system
spec:
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-gke-nightly-cluster-ubuntu-latest-wego-wego-test-app-72khhde7
  validation: client

